In [51]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score


from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

In [2]:
data = pd.read_csv('datasets/Student_Performance.csv')
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [4]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [5]:
data.duplicated().sum()

127

In [6]:
data.drop_duplicates(inplace=True)

In [7]:
data.duplicated().sum()

0

In [8]:
data.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [9]:
data.shape

(9873, 6)

In [10]:
data = data.rename(columns={'Hours Studied': 'study_hours', 'Previous Scores': 'scores',
                     'Extracurricular Activities': 'extra_activity', 'Sleep Hours': 'sleep_hours',
                     'Sample Question Papers Practiced': 'papers_practice', 'Performance Index': 'performance'
                       })

In [11]:
data.head()

,study_hours,scores,extra_activity,sleep_hours,papers_practice,performance
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [12]:
data.describe()

       study_hours       scores  sleep_hours  papers_practice  performance
count  9873.000000  9873.000000  9873.000000      9873.000000  9873.000000
mean      4.992100    69.441102     6.531652         4.583004    55.216651
std       2.589081    17.325601     1.697683         2.867202    19.208570
min       1.000000    40.000000     4.000000         0.000000    10.000000
25%       3.000000    54.000000     5.000000         2.000000    40.000000
50%       5.000000    69.000000     7.000000         5.000000    55.000000
75%       7.000000    85.000000     8.000000         7.000000    70.000000
max       9.000000    99.000000     9.000000         9.000000   100.000000

In [13]:
label = LabelEncoder()
df = data
df.extra_activity = label.fit_transform(df.extra_activity)
df.head()

,study_hours,scores,extra_activity,sleep_hours,papers_practice,performance
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [14]:
df.describe()

,study_hours,scores,extra_activity,sleep_hours,papers_practice,performance
count,9873.000000,9873.000000,9873.000000,9873.000000,9873.000000,9873.000000
mean,4.992100,69.441102,0.494986,6.531652,4.583004,55.216651
std,2.589081,17.325601,0.500000,1.697683,2.867202,19.208570
min,1.000000,40.000000,0.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,0.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,0.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,1.000000,8.000000,7.000000,70.000000
max,9.000000,99.000000,1.000000,9.000000,9.000000,100.000000

In [15]:
x = data.drop(columns='performance')
x.columns

Index(['study_hours', 'scores', 'extra_activity', 'sleep_hours',
       'papers_practice'],
      dtype='object')

In [16]:
x= x.values

In [17]:
y = data['performance']
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: performance, Length: 9873, dtype: float64

In [18]:
col_transform = ColumnTransformer([('extra_activity', OneHotEncoder(), [0])], remainder='passthrough')

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [20]:
print('x_train shape', x_train.shape); print('x_test shape',x_test.shape)

x_train shape (7898, 5)
x_test shape (1975, 5)

In [21]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [23]:
y_pred = model.predict(x_test)
y_pred

array([88.09795887, 52.46981909, 35.4608009 , ..., 40.63669835,
       42.3775456 , 63.0869466 ])

In [28]:
model.score(x_train, y_train)

0.9885797179620442

In [29]:
model.score(x_test, y_test)

0.9890582995494556

In [30]:
r2_score(y_pred, y_test)

0.9889463369858886

In [32]:
model.predict([[6, 70, 1, 7, 4]])

array([59.10568391])

In [33]:
model.predict([[7, 70, 1, 7, 4]])

array([61.96045657])

In [34]:
model.predict([[6, 70, 0, 7, 4]])

array([58.46115742])

In [36]:
model.predict([[6, 70, 1, 7, 9]])

array([60.07231397])

In [37]:
model.predict([[6, 70, 1, 8, 4]])

array([59.57757453])

In [38]:
model.predict([[8, 70, 1, 7, 4]])

array([64.81522923])

It seems study hours has the most impact on students performance.