In [71]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import load_wine

import warnings
warnings.filterwarnings('ignore')

In [72]:
wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [73]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [74]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [75]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [76]:
wine_df = pd.DataFrame(wine.data , columns=wine.feature_names)
wine_df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [77]:
wine_df['target'] = wine.target
wine_df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [78]:
wine_df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

In [97]:
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=42)

In [98]:
model_gaussian = GaussianNB()
model_gaussian.fit(X_train, y_train)

GaussianNB()

In [99]:
model_gaussian.predict(X_test[:10])

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2])

In [100]:
model_gaussian.score(X_test, y_test)

1.0

In [101]:
model_gaussian.predict_proba(X_test[:10])

array([[9.99991820e-01, 8.17986629e-06, 1.75844851e-31],
       [9.99999053e-01, 9.46598997e-07, 1.78086968e-25],
       [1.13448660e-18, 1.99953560e-03, 9.98000464e-01],
       [9.99999999e-01, 7.71694277e-10, 4.13905530e-37],
       [4.85016095e-07, 9.99999515e-01, 1.99877483e-22],
       [1.00000000e+00, 2.47066704e-12, 1.42452382e-33],
       [7.95594246e-11, 1.00000000e+00, 6.55702700e-13],
       [3.15918793e-21, 4.37517039e-12, 1.00000000e+00],
       [1.94710799e-04, 9.99805289e-01, 5.67647705e-29],
       [2.42169478e-15, 5.33549614e-04, 9.99466450e-01]])

In [102]:
model_multi = MultinomialNB()
model_multi.fit(X_train, y_train)

MultinomialNB()

In [103]:
model_multi.score(X_test, y_test)

0.8888888888888888

In [104]:
model_multi.predict(X_test[:10])

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 0])

In [105]:
model_multi.predict_proba(X_test[:10])

array([[8.37425054e-01, 1.27497079e-02, 1.49825239e-01],
       [9.99999994e-01, 2.67585322e-13, 5.89999253e-09],
       [5.93636747e-08, 1.38682167e-01, 8.61317774e-01],
       [1.00000000e+00, 1.64526232e-24, 3.88762363e-18],
       [9.57868054e-07, 8.57569472e-01, 1.42429570e-01],
       [1.00000000e+00, 8.82312670e-21, 6.64334557e-15],
       [2.11365082e-06, 9.23346035e-01, 7.66518514e-02],
       [1.66961292e-05, 8.46131247e-04, 9.99137173e-01],
       [8.68079638e-03, 9.00926343e-01, 9.03928604e-02],
       [8.33609491e-01, 4.53371124e-05, 1.66345172e-01]])