In [71]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [13]:
df = pd.read_csv('datasets/heart_disease.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [14]:
df.shape

(918, 12)

In [15]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [16]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

Dealing with outliers 

RestingBP

In [17]:
df['RestingBP_z_score'] = (df.RestingBP - df.RestingBP.mean()) / df.RestingBP.std()

In [18]:
df[df['RestingBP_z_score'] > 3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingBP_z_score
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0,3.111322
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1,3.651449
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1,3.651449
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1,3.651449
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1,3.111322
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1,3.651449
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1,3.219347

In [19]:
df[df['RestingBP_z_score'] < -3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,RestingBP_z_score
449,55,M,NAP,0,0,0,Normal,155,N,1.5,Flat,1,-7.151097

In [20]:
df = df[(df['RestingBP_z_score']>-3) & (df['RestingBP_z_score']<3)]
df.shape

(910, 13)

In [21]:
df.drop('RestingBP_z_score', axis=1, inplace=True)

In [25]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [26]:
df.shape

(910, 12)

Cholesterol

In [28]:
df['Cholesterol_z_score'] = (df.Cholesterol - df.Cholesterol.mean()) / df.Cholesterol.std()
df.shape

(910, 13)

In [29]:
df[df['Cholesterol_z_score']>3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Cholesterol_z_score
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1,3.022389
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1,3.700388
616,67,F,NAP,115,564,0,LVH,160,N,1.6,Flat,0,3.343064

In [30]:
df[df['Cholesterol_z_score']<-3]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease, Cholesterol_z_score]
Index: []

In [33]:
df = df[(df['Cholesterol_z_score']>-3) & (df['Cholesterol_z_score']<3)]
df.shape

(907, 13)

In [34]:
df.drop('Cholesterol_z_score', axis=1, inplace=True)

In [35]:
df.shape

(907, 12)

In [36]:
df.FastingBS.unique()

array([0, 1], dtype=int64)

In [37]:
df.MaxHR.unique()

array([172, 156,  98, 108, 122, 170, 142, 130, 120,  99, 145, 140, 137,
       150, 166, 165, 125, 160, 164, 138, 178, 112, 118, 127, 114, 154,
       155,  87, 148, 100, 168, 184, 121, 153, 134,  96, 174, 175, 144,
        82, 135, 115, 128, 116,  94, 110,  92, 180, 152, 124, 185, 139,
       190, 146, 158, 132, 176, 119, 188, 162, 105,  90, 136, 167, 129,
       102, 143, 103,  91, 126,  93, 131, 149, 123, 182, 141,  77, 109,
       133, 179, 113, 104,  95,  72,  97, 117,  86,  63, 157,  83,  60,
       163,  67,  78,  84, 106, 111,  80, 107, 161,  69,  88,  73, 159,
       151, 181, 186, 177, 173, 169, 171, 147,  71, 192, 194, 187, 202],
      dtype=int64)

MaxHR

In [38]:
df['MaxHR_z_score'] = (df.MaxHR - df.MaxHR.mean()) / df.MaxHR.std()

In [39]:
df[df['MaxHR_z_score']>3]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease, MaxHR_z_score]
Index: []

In [40]:
df[df['MaxHR_z_score']<-3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,MaxHR_z_score
390,51,M,ASY,140,0,0,Normal,60,N,0.0,Flat,1,-3.024379

In [41]:
df = df[(df['MaxHR_z_score']>-3) & (df['MaxHR_z_score']<3)]
df.shape

(906, 13)

In [42]:
df.drop('MaxHR_z_score', axis=1, inplace=True)

In [43]:
df.shape

(906, 12)

In [44]:
df.Oldpeak.unique()

array([ 0. ,  1. ,  1.5,  2. ,  3. ,  4. ,  0.5,  2.5,  5. ,  0.8,  0.7,
        1.4,  2.1,  0.4,  0.2,  1.7,  2.2,  0.1,  1.6,  1.3,  0.3,  1.8,
        2.6, -0.9,  2.8, -2.6, -1.5, -0.1,  0.9,  1.1,  2.4, -1. , -1.1,
       -0.7, -0.8,  3.7,  1.2, -0.5, -2. ,  1.9,  3.5,  0.6,  3.1,  2.3,
        3.4,  3.6,  4.2,  3.2,  5.6,  3.8,  2.9,  6.2,  4.4])

Oldpeak

In [45]:
df['Oldpeak_z_score']= (df.Oldpeak - df.Oldpeak.mean()) / df.Oldpeak.std()

In [46]:
df[df['Oldpeak_z_score']>3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Oldpeak_z_score
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1,3.864805
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0,3.113508
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1,4.428278
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1,3.113508
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1,4.991751
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1,3.301333

In [47]:
df[df['Oldpeak_z_score']<-3]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Oldpeak_z_score
324,46,M,ASY,100,0,1,ST,133,N,-2.6,Flat,1,-3.272516

In [49]:
df = df[(df['Oldpeak_z_score']>-3)& (df['Oldpeak_z_score']<3)]

In [50]:
df.shape

(899, 13)

In [51]:
df.drop('Oldpeak_z_score', axis=1, inplace=True)

In [52]:
df.shape

(899, 12)

In [53]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [56]:
heart_df = pd.get_dummies(df, drop_first=True)
heart_df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1

In [57]:
X = heart_df.drop('HeartDisease', axis=1)
y = heart_df.HeartDisease

In [63]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled[:2]

array([[-1.42815446,  0.46590022,  0.84963584, -0.5503622 ,  1.38431998,
        -0.85546862,  0.515943  ,  2.06332497, -0.5349047 , -0.22955001,
         0.80970176, -0.48989795, -0.8229452 , -0.99888827,  1.13469459],
       [-0.47585532,  1.63471366, -0.16812204, -0.5503622 ,  0.7529728 ,
         0.13751561, -1.93819859, -0.48465463,  1.86949191, -0.22955001,
         0.80970176, -0.48989795, -0.8229452 ,  1.00111297, -0.88129441]])

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [68]:
models = {
    'svm':{
        'model': SVC(),
        'params': {
            'C': range(1, 30) ,
            'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
        }
    }, 
    'logistic_regression':{
        'model': LogisticRegression(),
        'params': {
            'C':[1, 5, 10]
        }

    }, 
    'random_forest':{
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators' : [1, 5, 10]
        }

    }
}

In [72]:
scores = []
for model_name, mp in models.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv= 5, return_train_score= False)
    clf.fit(X_train, y_train)
    scores.append({
        'model' : model_name,
        'best_score' : clf.best_score_,
        'best_params' : clf.best_params_
    })

In [73]:
scores_result = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
scores_result

                 model  best_score                    best_params
0                  svm    0.866502  {'C': 1, 'kernel': 'sigmoid'}
1  logistic_regression    0.849796                       {'C': 1}
2        random_forest    0.842861            {'n_estimators': 5}

PCA

In [83]:
from sklearn.decomposition import PCA
pca = PCA(0.95)
X_pca = pca.fit_transform(X)
X.shape , X_pca.shape

((899, 15), (899, 2))

In [84]:
X_pca

array([[ 93.12962152, -29.67914603],
       [-16.33851633, -14.7998355 ],
       [ 82.66962658,  38.9118718 ],
       ...,
       [-68.22608631,  17.69794714],
       [ 40.02624242, -33.4650307 ],
       [-20.6125201 , -37.61693802]])

In [85]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.2, random_state= 30)

In [86]:
result = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
result

                 model  best_score                    best_params
0                  svm    0.866502  {'C': 1, 'kernel': 'sigmoid'}
1  logistic_regression    0.849796                       {'C': 1}
2        random_forest    0.842861            {'n_estimators': 5}